app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('bangalore/',bangalore,name='bangalore'),
    path('chennai/',chennai,name='chennai'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('hyderabad/',hyderabad,name='hyderabad'),
    path('mumbai/',mumbai,name='mumbai'),
]

project_08/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def bangalore(request):
    return render(request,'bangalore.html')
def chennai(request):
    return render(request,'chennai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def hyderabad(request):
    return render(request,'hyderabad.html')
def mumbai(request):
    return render(request,'mumbai.html')

templates/bangalore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome To Bangalore</h1>
        <a href="{% url 'app1:chennai' %}">Next To Chennai</a><br>
        <a href="{% url 'app2:hyderabad' %}">Next To hyderabad</a><br>
        <a href="{% url 'app2:mumbai' %}">Next To mumbai</a><br>
    </center>
    
</body>
</html>

templates/chennai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome To Chennai</h1>
        <a href="{% url 'app1:bangalore' %}">Next To Banaglore</a><br>
        <a href="{% url 'app2:hyderabad' %}">Next To hyderabad</a><br>
        <a href="{% url 'app2:mumbai' %}">Next To mumbai</a><br>
    </center>
</body>
</html>

templates/hyderabad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome To hyderabad</h1>
        <a href="{% url 'app1:bangalore' %}">Next To Banaglore</a><br>
        <a href="{% url 'app1:chennai' %}">Next To chennai</a><br>
        <a href="{% url 'app2:mumbai' %}">Next To mumbai</a><br>
    </center>
</body>
</html>

templates/mumbai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome To Mumbai </h1>
        <a href="{% url 'app1:bangalore' %}">Next To Banaglore</a><br>
        <a href="{% url 'app1:chennai' %}">Next To chennai</a><br>
        <a href="{% url 'app2:hyderabad' %}">Next To hyderabad</a><br>
</body>
</html>